import "server-only";
import { randomBytes } from "node:crypto";
import { env } from "../env";

/**
 * Object storage behind one interface.
 *
 * `local` writes under STORAGE_LOCAL_DIR and is what `npm run dev` uses.
 * `s3` is the production shape — any S3-compatible bucket. Application code
 * only ever holds opaque keys, so switching drivers is an environment change,
 * not a code change.
 *
 * The drivers themselves live in sibling modules and are loaded on demand:
 * `mediaUrl` is called by every page that renders a report card, and it has no
 * business dragging the filesystem into that bundle.
 */
export interface StorageProvider {
  readonly name: string;
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<Buffer | null>;
  delete(key: string): Promise<void>;
}

/** Keys are generated by us, but they reach a filesystem — validate anyway. */
export function assertSafeKey(key: string): void {
  if (!/^[a-z0-9/_-]+\.[a-z0-9]+$/i.test(key) || key.includes("..")) {
    throw new Error("Invalid storage key");
  }
}

/**
 * Objects under this prefix are national identity cards. Nothing here is ever
 * served by `/api/media`, and `mediaUrl` refuses to produce a URL for one — the
 * only way to read one is the staff route, which checks a role and writes an
 * audit entry.
 *
 * The prefix is the mechanism: a future call site that forgets the rule gets an
 * exception rather than a public link.
 */
export const PRIVATE_KEY_PREFIX = "identity/";

export function isPrivateKey(key: string): boolean {
  return key.startsWith(PRIVATE_KEY_PREFIX);
}

/**
 * Browser-facing URL for a stored object. Pure: derived from configuration
 * alone, so it is safe to call from any server component.
 */
export function mediaUrl(key: string): string {
  if (isPrivateKey(key)) {
    throw new Error("Refusing to build a public URL for a private object");
  }
  if (env.storageDriver === "s3" && env.s3.publicBaseUrl) {
    return `${env.s3.publicBaseUrl.replace(/\/$/, "")}/${key}`;
  }
  // Local files, and S3 buckets that are not public, stream through our own
  // handler so access stays under application control.
  return `/api/media/${key}`;
}

let cached: Promise<StorageProvider> | undefined;

export function storage(): Promise<StorageProvider> {
  if (cached) return cached;

  cached = (async (): Promise<StorageProvider> => {
    if (env.storageDriver === "s3") {
      const { S3StorageProvider } = await import("./storage-s3");
      const { endpoint, region, bucket, accessKeyId, secretAccessKey } = env.s3;
      if (!endpoint || !region || !bucket || !accessKeyId || !secretAccessKey) {
        throw new Error(
          "STORAGE_DRIVER=s3 requires S3_ENDPOINT, S3_REGION, S3_BUCKET, S3_ACCESS_KEY_ID and S3_SECRET_ACCESS_KEY.",
        );
      }
      return new S3StorageProvider({ endpoint, region, bucket, accessKeyId, secretAccessKey });
    }

    const { LocalStorageProvider } = await import("./storage-local");
    return new LocalStorageProvider(env.storageLocalDir);
  })();

  return cached;
}

/** Unguessable key, grouped by month so old objects are easy to sweep. */
export function newStorageKey(prefix: string, extension: string): string {
  const now = new Date();
  const month = `${now.getUTCFullYear()}${String(now.getUTCMonth() + 1).padStart(2, "0")}`;
  return `${prefix}/${month}/${randomBytes(16).toString("hex")}.${extension}`;
}
