import "server-only";
import { randomBytes } from "node:crypto";
import { env } from "../env";

/**
 * Object storage behind one interface.
 *
 * `local` writes under STORAGE_LOCAL_DIR and is what `npm run dev` uses.
 * `s3` is the production shape — any S3-compatible bucket. Application code
 * only ever holds opaque keys, so switching drivers is an environment change,
 * not a code change.
 *
 * The drivers themselves live in sibling modules and are loaded on demand:
 * `mediaUrl` is called by every page that renders a report card, and it has no
 * business dragging the filesystem into that bundle.
 */
export interface StorageProvider {
  readonly name: string;
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<Buffer | null>;
  delete(key: string): Promise<void>;
}

/** Keys are generated by us, but they reach a filesystem — validate anyway. */
export function assertSafeKey(key: string): void {
  if (!/^[a-z0-9/_-]+\.[a-z0-9]+$/i.test(key) || key.includes("..")) {
    throw new Error("Invalid storage key");
  }
}

/**
 * Browser-facing URL for a stored object. Pure: derived from configuration
 * alone, so it is safe to call from any server component.
 *
 * Everything reachable through this function is public by nature: report
 * photos and profile pictures. Identity documents are not objects — they are
 * columns, readable only through an audited staff route — so there is no
 * private key for this to have to refuse.
 */
export function mediaUrl(key: string): string {
  if (env.storageDriver === "s3" && env.s3.publicBaseUrl) {
    return `${env.s3.publicBaseUrl.replace(/\/$/, "")}/${key}`;
  }
  // Local files, and S3 buckets that are not public, stream through our own
  // handler so access stays under application control.
  return `/api/media/${key}`;
}

let cached: Promise<StorageProvider> | undefined;

export function storage(): Promise<StorageProvider> {
  if (cached) return cached;

  cached = (async (): Promise<StorageProvider> => {
    if (env.storageDriver === "s3") {
      const { S3StorageProvider } = await import("./storage-s3");
      const { endpoint, region, bucket, accessKeyId, secretAccessKey } = env.s3;
      if (!endpoint || !region || !bucket || !accessKeyId || !secretAccessKey) {
        throw new Error(
          "STORAGE_DRIVER=s3 requires S3_ENDPOINT, S3_REGION, S3_BUCKET, S3_ACCESS_KEY_ID and S3_SECRET_ACCESS_KEY.",
        );
      }
      return new S3StorageProvider({ endpoint, region, bucket, accessKeyId, secretAccessKey });
    }

    if (env.storageDriver === "blob") {
      const { BlobStorageProvider } = await import("./storage-blob");
      if (!env.blobToken) {
        throw new Error(
          "STORAGE_DRIVER=blob requires BLOB_READ_WRITE_TOKEN. Creating a Blob store in the " +
            "Vercel dashboard sets it for you; redeploy afterwards so the deployment picks it up.",
        );
      }
      return new BlobStorageProvider(env.blobToken);
    }

    // The filesystem is not writable on a serverless host, and the failure
    // otherwise surfaces as ENOENT on `mkdir /var/task/storage` in the middle
    // of an upload — a stack trace that says nothing about the actual mistake.
    // Refuse at the boundary instead, naming both ways out.
    if (env.isServerless) {
      throw new Error(
        "STORAGE_DRIVER=local cannot work on this host: the filesystem is read-only, so uploads " +
          "have nowhere to go. Use STORAGE_DRIVER=blob (create a Blob store in the Vercel " +
          "dashboard, which sets BLOB_READ_WRITE_TOKEN) or STORAGE_DRIVER=s3 with any " +
          "S3-compatible bucket.",
      );
    }

    const { LocalStorageProvider } = await import("./storage-local");
    return new LocalStorageProvider(env.storageLocalDir);
  })();

  // A rejected promise left in the cache would be re-thrown for the life of
  // the process: one bad startup and this instance can never upload again,
  // even once the cause has passed. Forget the failure and let the next
  // caller try afresh.
  cached.catch(() => {
    cached = undefined;
  });

  return cached;
}

/** Unguessable key, grouped by month so old objects are easy to sweep. */
export function newStorageKey(prefix: string, extension: string): string {
  const now = new Date();
  const month = `${now.getUTCFullYear()}${String(now.getUTCMonth() + 1).padStart(2, "0")}`;
  return `${prefix}/${month}/${randomBytes(16).toString("hex")}.${extension}`;
}
